# Site Settings
site_name: Ben's AWS Guide
site_url: https://aws.bencassani.com/
# Git Hub Settings
repo_url: https://github.com/bencoding/AWS_Docs/
repo_name: bencoding/AWS_Docs
# edit_uri: ""
# Theme Settings
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - search.suggest
    - navigation.instant
    - navigation.top
     - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - search
     - git-revision-date
    - tags
copyright: Copyright &copy; 2021 Ben Cassani
# Customization
extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bencoding
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bencassani
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/bencassani
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Page tree
nav:
  - Home: index.md
  - Architecture:
    - Start: getting-started.md
    - Decision: architecture/decisions.md
    - Resiliency: architecture/resilence.md
  - Compute: 
    -  Options: compute/options.md
    -  Fargate: compute/fargate.md
    -  Lambda: compute/lambda.md
    -  Serverless: compute/serverless.md
    -  Use Cases: compute/usecases.md
  - Database:
      - Options: database/options.md
  - Storage:
    - Options: storage/options.md
  - Monitor:
    - Options: monitor/options.md
  - Messaging:
    - Options: messaging/options.md
  - Network:
    - Options: network/options.md
  - Storage:
    - Options: storage/options.md
  - Analytics:
    - Options: analytics/options.md
  - ML-AI:
    - Options: analytics/options.md
  - Security:
    - Options: security/options.md
  - Cost:
    - Options: cost/costmodel.md
  - Optimize: 
    -  Basics: optimize/terraform.md






